### ISSUE TITLE
Not working for multiplayer 

### ISSUE THREAD

**Issue by rainbowboii** [jjohnsnaill/SubworldLibrary#11]
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
1.Enable "The Stars Above"
2.Load up tmodloader server
3.load into server and attempt to go to a subworld.
4.It not work
When i tried to communicate with dev of "the stars above" He told, its depends on Subworld lib.
Fix it pls.

**Comment by Xplodin** [comment]
I would love for this to work. If there is code that fixes it I wouldnt mind compiling it myself. But it seems there is none currently :(

**Comment by jjohnsnaill** [comment]
Better explained by #12.
