### ISSUE TITLE
Game crashing in subword/ when coming back to overworld (singleplayer)

### ISSUE THREAD

**Issue by loicpantano** [jjohnsnaill/SubworldLibrary#15]
When i'm in a subworld/returning to the main world this error will randomly appear, make tmodloader crash and i will need to reload a backup of my world/char .

## Mods installed
[
  "Census",
  "CalValEX",
  "CalamityModMusic",
  "CalamityMod",
  "BossesAsNPCs",
  "BossChecklist",
  "AutoReroll",
  "ArmorReforge",
  "AlchemistNPCLite",
  "DialogueTweak",
  "imkSushisMod",
  "ImproveGame",
  "StarsAbove",
  "Lights",
  "LootBeams",
  "MagicStorage",
  "MaxStackExtra",
  "OmniSwing",
  "OreExcavator",
  "RecipeBrowser",
  "RecipeBrowserToMagicStorage",
  "ShorterRespawn",
  "SubworldLibrary",
  "InfernumMode",
  "WingSlotExtra",
  "WMITF"
]

## Steps to recreate 

1. Launch the game with those mods enabled
2. Go to a subworld with the spatial disk from stars above
3. Wait/try to go back to the overworld and the error will have a chance to appear

## Error message
Error message when i try to go back to my homeworld
![](https://i.imgur.com/Ox2cI30.png)

Is a fix available/possible ?

Thank you

**Comment by loicpantano** [comment]
Update: it seems that the problem came from the fact that the world was sync with the cloud
Desactivating the sync seems to fix the problem

**Comment by jjohnsnaill** [comment]
Presumably fixed in 2.2.2.
