### ISSUE TITLE
Loss of Configuration on World Change

### ISSUE THREAD

**Issue by Jar-M** [jjohnsnaill/SubworldLibrary#16]
There are a few configuration options that are lost upon entering/leaving a subword.
1. UI scale
2. Fargo's in world configs, eg: Eternity toggle & accessory ability toggle
3. Calamity Difficulty selection

**Comment by jjohnsnaill** [comment]
Adding the ability for mods to fix reset variables in the next update. The UI scale issue is a longstanding bug that I'm still attempting to fix every now and then.
