### ISSUE TITLE
Subworld Discord??

### ISSUE THREAD

**Issue by stinker0** [jjohnsnaill/SubworldLibrary#19]
I've heard there is a subworld discord but nor the homepage, this github or the mod browser has a link to it.

If there is one, could i have link/put it to description?

Thanks in advance

**Comment by jjohnsnaill** [comment]
Subworld Library's Discord server is technically the GaMeTerraria Discord server, but I ended up removing the link to it because a ton of people asking "how do I use this mod???" kept joining. You can join that, though the forum thread or this repo should suffice.
