### ISSUE TITLE
crashing when enabled

### ISSUE THREAD

**Issue by NightOwl1504** [jjohnsnaill/SubworldLibrary#2]
im trying to play polarity mod but its dependant on subworldlibrary, which keeps crashing, i cant think of any reason why and i know its not polarity.

**Comment by NightOwl1504** [comment]
![image](https://user-images.githubusercontent.com/76790665/132959332-c03ecbba-4a9a-4bcc-8382-18acb0ab3664.png)

-this is the error

**Comment by jjohnsnaill** [comment]
As far as I'm aware this is not an issue on Subworld Library's end.
