### ISSUE TITLE
Can't load into InfernumMode/LostColosseum subworld in multiplayer

### ISSUE THREAD

**Issue by Ballsfish** [jjohnsnaill/SubworldLibrary#21]
Can't load into InfernumMode/LostColosseum subworld in multiplayer, gets stuck on "saving map data 100%" and spits out an error log.
[server2.log](https://github.com/jjohnsnaill/SubworldLibrary/files/11691175/server2.log)

**Comment by jjohnsnaill** [comment]
Fixed in 2.2.1.3.
