### ISSUE TITLE
Game Freezes After Loading Into Subworld

### ISSUE THREAD

**Issue by Savaesthetic** [jjohnsnaill/SubworldLibrary#24]
Im Playing Singlepler
Tmodloader is v1.4.3-legacy beta (1.4.3.6)
Subworld Library v2.2.1.1
Stars Above v1.4.5.5

Like the title says, whenever I try to load into one of the Stars Above planets, the game freezes. It seems like the map loading is finishing and the issue might be occurring during spawn in. I've attached an image of what the issue looks like, but it doesn't seem like I'm seeing any exceptions being thrown in the tmoadloader client.log file. If there is any other way I can grab a log file to better help with diagnosing the issue let me know.

The subworld library mod was working earlier today, 7/30/2023, but I am unsure of what version I was on. I believe that tmodloader automatically updates the mods on launch which would mean I should have been on 2.2.1 at least.

![image](https://github.com/jjohnsnaill/SubworldLibrary/assets/56328886/709b87f5-a60d-46a7-b010-1a28220f07a1)

**Comment by GabeHasWon** [comment]
I am also experiencing this issue. Before the recent update, the subworld worked perfectly fine. Now, I'm softlocked when entering the subworld.

**Comment by xXDarkNovaXx** [comment]
Same here
I need to restart Terraria to bring me back to the normal Terraria World

**Comment by jjohnsnaill** [comment]
Fixed in 2.2.1.3.
