### ISSUE TITLE
Issue with multiplayer and most recent update

### ISSUE THREAD

**Issue by The-Synthesizer** [jjohnsnaill/SubworldLibrary#27]
When trying to load a world in multiplayer in 1.4.3 with Subworld Library enabled, it brings up a mod loading screen and disables Subworld library and any mods that have Subworld Library as a dependency, like The Stars Above. 
I am still able to join the world, but with missing items from the disabled mods.

**Comment by jjohnsnaill** [comment]
Fixed in 2.2.1.3.
