### ISSUE TITLE
Loading subworld sometimes gets stuck at 100%

### ISSUE THREAD

**Issue by LorenzoPapi** [jjohnsnaill/SubworldLibrary#32]
I've created a dedicated server with some friends and sometimes when we try to teleport to another subworld it just gets stuck to the "100% loaded" screen. In particular, we are having issues teleporting to the first Subworld Of the Stars Above mod.

**Mods list**
ModLoader (tModLoader) v2023.6.25.32
CalamityMod (Calamity Mod) v2.0.3.4
CalamityModMusic (Calamity Mod Music) v2.0.3.1
AlchemistNPCLite (AlchemistNPC Lite) v1.9.2
BossChecklist (Boss Checklist) v1.6.2.2
CalValEX (Calamity's Vanities) v11.0.8
SerousCommonLib (absoluteAquarian Utilities) v1.0.4.1
MagicStorage (Magic Storage) v0.6.0.3
RecipeBrowser (Recipe Browser) v0.10.2
SharedMap (Shared World Map) v0.1.3.4
SmarterCursor (Smarter Cursor) v1.3.1
**SubworldLibrary (Subworld Library) v2.2.1.2
StarsAbove ([c/EC1B9D:The Stars Above]) v1.5.2.2**
UnCalamityModMusic (Vanilla Calamity Mod Music) v1.0.10
WheresMyItems (Where's My Items) v0.7.0.2

**Server Log**: [server.log](https://gist.github.com/LorenzoPapi/9630440dbdb15a1890ae1a641ff82393)

**Comment by jjohnsnaill** [comment]
Fixed in 2.2.2.
