### ISSUE TITLE
The stars above(Multiplayer) after death in subworld infinity "Saving map data 100%"

### ISSUE THREAD

**Issue by MRLap4** [jjohnsnaill/SubworldLibrary#39]
After I die in the subworld, I am periodically sent to an endless load, and sometimes crashes with an error(Invalid operation in this state)

[server17.log](https://github.com/jjohnsnaill/SubworldLibrary/files/14893189/server17.log)
[server15.log](https://github.com/jjohnsnaill/SubworldLibrary/files/14893197/server15.log)
![image](https://github.com/jjohnsnaill/SubworldLibrary/assets/166215333/6ab2649c-d6c4-4c77-810e-20af14d290cd)

**Comment by jjohnsnaill** [comment]
Fixed in 2.2.2.2.
