### ISSUE TITLE
Background issue

### ISSUE THREAD

**Issue by Silvernova115** [jjohnsnaill/SubworldLibrary#4]
When im in the underworld, the background doesnt show. it does show up if I disable this mod.

**Comment by Opnoob007** [comment]
I also have this issue if I use this mod please fix this

**Comment by WinterEquinoxAlpha** [comment]
Error reproduced on my machine as well

**Comment by TerraLance** [comment]
Reproduced here

**Comment by YellowBirb** [comment]
I noticed this too, and im not sure whether underworld enemies have stopped spawning because of this. v1.4.3.6 tModLoader v2022.6.96.4

**Comment by jjohnsnaill** [comment]
Fixed in 2.0.1.2. It was just the background that wasn't appearing.
