### ISSUE TITLE
Subworld processes do not inherit commandline arguments

### ISSUE THREAD

**Issue by CreepyCre** [jjohnsnaill/SubworldLibrary#40]
Subworld processes do not inherit commandline arguments. Relevant arguments may include:

- `-modpath` (subserver won't even load the required mods if `-modpath` is actually used to load mods)
- `-modpack`
- `-port` (if main server is not running on port 7777, the subserver would be exposed on 7777. Not sure about the implications)
- `-ip` (same thought process as `-port`)
- `-secure`
- `-forcepriority`
- `-difficulty` (not sure if this is actually relevant)
- `-config` (may contain further server configuration)

Passing `-modpath` and `-modpack` is critical for the subserver to actually load mods correctly.

**Comment by jjohnsnaill** [comment]
Will fix `-modpath`, `-modpack`, `-secure` and `-forcepriority` not being inherited in 2.2.2.2!
`-port` and `-ip` don't need inheriting since subservers don't use them, and `-difficulty` should be synced separately.
I'll have to take a closer look at `-config` in case there's something subservers shouldn't inherit.

**Comment by rehashedsalt** [comment]
The [Terraria Wiki](https://terraria.wiki.gg/wiki/Guide:Setting_up_a_Terraria_server#Making_a_configuration_file) has what looks to be an exhaustive list of all configs for vanilla, and tML maintains a list on [their GitHub Wiki](https://github.com/tModLoader/tModLoader/wiki/Command-Line). One more thing that jumps out as potentially relevant is `steamworkshopfolder`.

**Comment by jjohnsnaill** [comment]
Will make subservers inherit `-steamworkshopfolder` as well, thanks for letting me know!
The `world` and `seed` config options seem a little dangerous to subworlds, but configs load before SubLib so they should get overridden. Adding `-config` to the list.
