### ISSUE TITLE
One of mods which use's subworld library corrupts character

### ISSUE THREAD

**Issue by ghost** [jjohnsnaill/SubworldLibrary#7]
When i enable mod which use's subworld library it corrupts the character but when i disable the mod it opens the character 
(sorry for my bad english im from differenct country)

**Comment by HeeboE** [comment]
Can you specify what mod and maybe some error codes/steps to recreate the problem

**Comment by Sasha118300** [comment]
**Mod**: bob blender **Steps to reproduce** 1. Open tModLoader 2. enable mod 3. Character gives (UnknownError) message

**Comment by Sasha118300** [comment]
anyone here?
